name: Angular Frontend CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      - name: Run Linter
        run: npx eslint . --ext .ts,.html
        working-directory: frontend

  test:
    name: Test and Upload Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      - name: Run Tests with Coverage
        run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadless --code-coverage
        working-directory: frontend
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./frontend/coverage/frontend/lcov.info
          flags: frontend
          fail_ci_if_error: true
          verbose: true

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      - name: Check Formatting with Prettier
        run: npx prettier --check .
        working-directory: frontend
      - name: Build
        run: npm run build -- --configuration production
        working-directory: frontend
      - name: Upload Angular build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angular-build
          path: frontend/dist
