name: Build and Release LaTeX Documentation

on:
  pull_request:
    paths:
      - 'doc/**'
      - '.github/workflows/documentation.yml'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile Software Architecture Specification
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: doc/SAS-Typecode_Registry

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./doc/main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}