name: Go

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.22
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go mod download
      working-directory: backend
    - name: Format Check
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "Go code is not properly formatted:"
          gofmt -d .
          exit 1
        fi
    - name: Lint
      run: go vet ./...
      working-directory: backend/cmd/app
    - name: Test
      run: go test -v ./...